sudo required

language: generic

services:
  - docker


before_install:
  - docker --version
  - docker-compose --version

install:
  - docker-compose build
  - sleep 15
  - docker ps -a
 


after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker-compose push

