sudo: required

language: generic

services:
  - docker

before_install:
  - docker --version
  - docker-compose --version
  - export $DOCKER_CONTENT_TRUST

install:
  - docker-compose build

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker-compose push
